config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :ratings, only: [:new, :create]
    resources :orders, only: [:new, :create, :show]
  end

  devise_for :companies
  resources :posts
  devise_for :users
  root "home#about"

  get 'home', to: 'home#home'
  get 'about', to: 'home#about'

  get '/user/profile', to: 'home#profile'
  get '/company/profile', to: 'home#company_profile'
  get '/user/services', to: 'home#services'

  get '/services/search', to: 'home#search'

  get '/user/services/search', to: 'home#filter'
  get '/company/services/search', to: 'services#filter'

  get '/company/posts', to: 'home#posts'

  get '/notification', to: 'home#notification'

  # get '/services/:service_id/payment', to: 'orders#payment', as: :payment
  # get '/pay', to: 'orders#pay'

  

end

app/views/shared/_alert.html.erb
<% if notice %>
    <div class="flash-card notice alert alert-success alert-dismissible fade show fw-bold position-absolute top-2 ms-lg-4" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if alert %>
    <div class="flash-card notice alert alert-warning alert-dismissible fade show position-absolute top-2 ms-lg-4" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/shared/_card.html.erb
<div class="col card-div">
  <div class="card" style="width: 18rem;">
      <%= image_tag image, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">
              <%= title || "No Title" %>
          </h5>
          
          <p class="card-text para-justify"> <%= paragraph || "Our Website is made for the seamless user experience" %> </p>
        </div>
    </div>
</div>

app/views/shared/_company_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    
    <%= link_to image_tag('Pulse.png'), home_path, class: "nav-img" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav-ul navbar-nav me-auto mb-2 mb-lg-0 ms-4">
      
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active active fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Services", services_path, class: "nav-link active fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", company_posts_path, class: "nav-link active fw-bold" %>
        </li>
        
      </ul>
      <ul class="navbar-nav ms-4 nav-ul">
      <li class="nav-item me-2">
        <%= link_to notification_path, class: "nav-link active fw-bold" do %>
          <% if @notify > 0 %>
            <i class="fa-solid fa-bell position-relative fa-beat"><i class="fa-solid fa-bowling-ball position-absolute start-50 fa-2xs" style="color: #ff0000;"></i></i>
          <% else %>
            <i class="fa-solid fa-bell"></i>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item me-2">
        <%= link_to "Profile", company_profile_path, class: "nav-link active fw-bold" %>
      </li>
      <% if company_signed_in? %>
        <li class="nav-item me-2">
          <%= button_to "Logout", destroy_company_session_path, method: :delete, class: "nav-link active fw-bold" %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_company_registration_path, class: "nav-link active fw-bold" %>
      </li>

      <li class="nav-item">
        <%= link_to "Log In", new_company_session_path, class: "nav-link active fw-bold" %>
      </li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    
    <%= link_to image_tag('Pulse.png'), home_path, class: "nav-img" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav-ul navbar-nav me-auto mb-2 mb-lg-0 ms-4">
      
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Services", user_services_path, class: "nav-link active fw-bold" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link active fw-bold" %>
        </li>
        
      </ul>
      <ul class="nav-ul navbar-nav ms-4">
      <li class="nav-item me-2">
        <%= link_to notification_path, class: "nav-link active fw-bold" do %>
          <% if @notify > 0 %>
            <i class="fa-solid fa-bell position-relative fa-beat"><i class="fa-solid fa-bowling-ball position-absolute start-50 fa-2xs" style="color: #ff0000;"></i></i>
          <% else %>
            <i class="fa-solid fa-bell"></i>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item me-2">
        <%= link_to "Profile", user_profile_path, class: "nav-link active fw-bold" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item me-2">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link active fw-bold" %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active fw-bold" %>
      </li>

      <li class="nav-item">
        <%= link_to "Log In", new_user_session_path, class: "nav-link active fw-bold" %>
      </li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/shared/_notification_card.html.erb
<% instance = notification.to_notification %>
    <li class="bg-light p-2 pb-1 m-2 border rounded">
      <span>Sent at: <%= notification&.created_at.strftime('%A, %B %e, %Y %l:%M %p %Z').to_s %></span>
      <p><%= instance.message %></p>
</li>

app/views/shared/_price_select_box.html.erb
<div class="field col-lg-3 ms-2">
    <select data-action="change->search#priceFilter" class="form-select bg-light fw-bold">
        <option selected value="all">Price</option>
        <option value="1">0 - 99</option>
        <option value="2">100 - 299</option>
        <option value="3">300 - 599</option>
        <option value="4">600 +</option>
    </select>
</div>

app/views/shared/_rating_select_box.html.erb
<div class="field col-lg-3 ms-2">
    <select data-action="change->search#ratingFilter" class="form-select bg-light fw-bold">
        <option selected value="all">Ratings</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>
</div>

app/views/shared/_ratings_input.html.erb
<% if @service.orders.where("user_id=?", current_user.id).exists? && !@service.ratings.where("user_id=?", current_user.id).exists?  %>
<h2>Add Ratings</h2>
<%= form_with model: [ @service, @service.ratings.build ] do |form| %>
<div>
<% (1..5).each do |r| %>
    <% radio_button_tag :ratings, r, false, class: "radio-button" %>
    <i data-action="click->rating#handlechange" data-rating-target="radio" class="fa-solid fa-star fa-beat">
        <%= form.radio_button :ratings, r, checked: false, class:"visually-hidden" %>
      
        <%= form.label r, class:"visually-hidden" %>
    </i>
  <% end %>

</div>

<div data-rating-target="submitbtn" class="my-2">
  <%= form.submit "submit", class: "btn button-purple rounded text-white visually-hidden" %>
</div>
    <% end %>

<% end %>

app/views/shared/_search_bar.html.erb
<div class="field col-lg-7">
    <% if flag %>
        <input data-action="input->search#filterPosts" type="text" placeholder="Search" class="form-control bg-light border rounded fw-bold mb-4" />
    <% else %>
        <input data-action="input->search#filter" type="text" placeholder="Search" class="form-control bg-light border rounded fw-bold mb-4" />
    <% end %>
</div>

app/views/shared/_select_box.html.erb
<div class="field col-lg-3 ms-2">
    <select data-action=<%= action %> class="form-select bg-light fw-bold">
        <option selected value="all"><%= name %></option>
        <% val.each do |key, value| %>
            <option value=<%=key%> > <%=value%></option>
        <% end %>
    </select>
</div>

app/views/shared/_service_post_card.html.erb
<div data-search-target="post" class="card w-75 mb-3 bg-light"> 
  <div class="card-body p-1">
    <div class="row">

      <div class="col-md col-lg-3 d-flex justify-content-center align-items-center">
        <% if service.service_post_image.attached? %>
          <%= image_tag service.service_post_image, height: 160, width: 180 %>
        <% else %>
          <%= image_tag "eco.avif", height: 160, width: 180 %>
        <% end %>
      </div>

      <div class="col-md">
      
        <div class="d-md-flex justify-content-between">
          <h2 data-search-target="name" class="card-title m-0"><%= service.title.capitalize %></h2>
          <h2 data-search-target="price" class="card-title m-0"><span class="badge rounded bg-dark price-tag">₹ <%= service.price %> </span></h2>
        </div>

        <h5 class="card-text text-secondary"><%= service.name %></h5>
        <div data-search-target="location" class="d-flex gap-2">
            <h4><span class="badge bg-black"> <%= service.city %></span> </h4>
        </div>

        <div class="d-flex justify-content-between">
          <h4 class="card-text text-secondary service-type">Type: <%= service.material %></h4>
          <% if service.avg_rating==0 %>
            <h5 class="card-text col-md"> Ratings: <%= service.avg_rating %>  </h5>
          <% else %>
            <div>
              <span class="card-text col-md"> Ratings: </span>
              <% (1..service.avg_rating).each do |r| %>
                <i class="fa-solid fa-star fa-lg my-1" style="color: #ffc800;"></i>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="d-flex justify-content-between align-items-center">  
          <div>
            <span data-search-target="rating" class="visually-hidden"><%= service.avg_rating %></span>
            <% if !company_signed_in? %>
              <div data-controller="rating" class="ms-5 col-md my-2 d-flex">

                <% if ratingflag && service.orders.where("user_id=?", current_user.id).exists? && !service.ratings.where("user_id=?", current_user.id).exists?  %>
                  <h6 class="me-2 my-1">Rate: </h6>

                  <%= form_with model: [ service, service.ratings.build ] do |form| %>
                    <div class="ratings-input d-flex">
                      <div>
                        <% (1..5).each do |r| %>
                          <% radio_button_tag :ratings, r, false, class: "radio-button" %>
                          <i data-action="click->rating#handlechange" data-rating-target="radio" class="fa-solid fa-star fa-beat">
                              <%= form.radio_button :ratings, r, checked: false, class:"visually-hidden" %>
                            
                              <%= form.label r, class:"visually-hidden" %>
                          </i>
                        <% end %>
                      </div>
                
                      <div data-rating-target="submitbtn" class="ms-1 m-0">
                          <%= form.submit "Submit", class: "rate-btn tn button-purple rounded text-white p-1 visually-hidden" %>
                      </div>
                    </div>
                  <% end %>

                <% end %>

              </div>
            <% end %>     
          </div>

          <div>

            <div class="col-md my-2">
              <!-- 
              <% if service.avg_rating==0 %>
                <h5 class="card-text col-md"> Ratings: <%= service.avg_rating %>  </h5>
              <% else %>
                <div>
                  <span class="card-text col-md"> Ratings: </span>
                  <% (1..service.avg_rating).each do |r| %>
                    <i class="fa-solid fa-star fa-lg my-1" style="color: #ffc800;"></i>
                  <% end %>
                </div>
              <% end %>
              -->
            </div>

            <% if !company_signed_in? %>
              <% if !orderFlag %>
                
              <% else %>
                <div class="col col-2 my-2">
                  <%= link_to "Order", new_service_order_path(service), class: "btn button-green fw-bold ms-lg-4" %>
                </div>
              <% end %>
            <% else %>
              <% if flag %>
                <div class="col text-end me-1">
                  <%= link_to "Edit", edit_service_path(service), class: "btn btn-warning fw-bold" %>
      
                  <%= link_to "Delete", service_path(service), class: "btn btn-danger fw-bold", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
                </div>
              <% end %>
            <% end %>
            
            
          </div>
        </div>


      </div>

    </div>
  </div>


  <% if false %>
   <div class="row">

      <span data-search-target="rating" class="visually-hidden"><%= service.avg_rating %></span>
      <% if !company_signed_in? %>
      <div data-controller="rating" class="ms-5 col-md my-2 d-flex">
        <% if ratingflag && service.orders.where("user_id=?", current_user.id).exists? && !service.ratings.where("user_id=?", current_user.id).exists?  %>
          <h6 class="me-2 my-1">Rate: </h6>
          <%= form_with model: [ service, service.ratings.build ] do |form| %>
          <div class="d-flex">
          <div>
          <% (1..5).each do |r| %>
              <% radio_button_tag :ratings, r, false, class: "radio-button" %>
              <i data-action="click->rating#handlechange" data-rating-target="radio" class="fa-solid fa-star fa-beat">
                  <%= form.radio_button :ratings, r, checked: false, class:"visually-hidden" %>
                
                  <%= form.label r, class:"visually-hidden" %>
              </i>
            <% end %>
          </div>
          
          <div data-rating-target="submitbtn" class="ms-1 m-0">
                  <%= form.submit "Submit", class: "rate-btn tn button-purple rounded text-white p-1 visually-hidden" %>
            </div>
          </div>
              <% end %>
          <% end %>
      </div>
      <% end %>

      <div class="col-md my-2">
        <!-- <% if service.avg_rating==0 %>
          <h5 class="card-text col-md"> Ratings: <%= service.avg_rating %>  </h5>
        <% else %>
          <div>
            <span class="card-text col-md"> Ratings: </span>
            <% (1..service.avg_rating).each do |r| %>
              <i class="fa-solid fa-star fa-lg my-1" style="color: #ffc800;"></i>
            <% end %>
          </div>
        <% end %>
        -->
        </div>
          <% if !company_signed_in? %>
            <% if !orderFlag %>
              
            <% else %>
              <div class="col col-2 my-2">
                <%= link_to "Order", new_service_order_path(service), class: "btn button-green fw-bold ms-lg-4" %>
              </div>
            <% end %>
          <% else %>
            <% if flag %>
              <div class="col text-end me-1">
                <%= link_to "Edit", edit_service_path(service), class: "btn btn-warning fw-bold" %>

                <%= link_to "Delete", service_path(service), class: "btn btn-danger fw-bold", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
              </div>
            <% end %>
          <% end %>
        
        
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_user_post_card.html.erb
<% if !post.flag && post.date >= Date.today %>
<div data-search-target="post"  class="card w-75 mb-3 bg-light"> 
  <div class="card-body p-1">
  <h4 class="post-contact-detail col-md text-end position-absolute top-0 end-0">Contact No: <%= post.phone_number %></h4>
  <div class="row">
    <div class="col-md col-lg-3 d-flex justify-content-center align-items-center">
      <% if post.user_post_image.attached? %>
        <%= image_tag post.user_post_image, height: 140, width: 180 %>
      <% else %>
        <%= image_tag "eco.avif", height: 140, width: 180 %>
      <% end %>
    </div>
    <div class="col-md">
        <h2 data-search-target="name" class="card-title"><%= post.name.capitalize %>  (<span><%= post.material_type.capitalize %></span>)</h2>
        <h6 class="card-text text-secondary">Address: <%= post.address %> </h6>
        <h4><span class="badge bg-black"><%= post.city.capitalize %> </span></h4>
        <div class="d-lg-flex justify-content-between">
            <h6 class="card-text text-secondary">Type: <%= post.material_type.capitalize %> </h6>
            <h6 class="card-text text-secondary">Date: <%= post.date %> </h6>
            <h6 class="card-text text-secondary">Time Available: <%= post.time_slot %> </h6>
        </div>
    </div>
  </div>
  <div class="row">
    <p class="card-text col-md">Description: <%= post.description.size==0 ? "NA" : post.description %>  </p>
    
    
      <% if !user_signed_in? %>
        <div class="col col-lg-2 my-2">
          <%= link_to "Request", post_path(post), class: "btn button-green fw-bold ms-2" %>
        </div>
      <% else %>
        <div class="col text-end me-1">
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-warning fw-bold" %>

          <%= link_to "Destroy", post_path(post), class: "btn btn-danger fw-bold", data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
          } %>
        </div>
      <% end %> 
  </div>
  </div>
</div>
<% else %>
<div data-search-target="post" class="expired-card card w-75 mb-3"> 
  <div class="card-body p-1">
  <h4 class="post-contact-detail text-end m-0 position-absolute top-0 end-0">Contact No: <%= post.phone_number %></h4>
  <div class="row">
    <div class="col-md col-lg-3 d-flex justify-content-center align-items-center">
      <% if post.user_post_image.attached? %>
        <%= image_tag post.user_post_image, height: 140, width: 180 %>
      <% else %>
        <%= image_tag "eco.avif", height: 140, width: 180 %>
      <% end %>
    </div>
    <div class="col-md">
        <h2 data-search-target="name" class="card-title"><%= post.name.capitalize %>  (<%= post.material_type.capitalize %>)</h2>
        <h6 class="card-text">Address: <%= post.address %> </h6>
        <h4><span class="badge bg-black"><%= post.city.capitalize %></span></h4>
        <div class="d-lg-flex justify-content-between">
            <h6 class="card-text">Type: <%= post.material_type.capitalize %> </h6>
            <h6 class="card-text">Date: <%= post.date %> </h6>
            <h6 class="card-text">Time Available: <%= post.time_slot %> </h6>
        </div>
    </div>
  </div>
  <div class="row">
    <p class="card-text col=md"> Description: <%= post.description.size==0 ? "NA" : post.description %>  </p>
    <div class="col-md col-2">
    <% if post.flag %>
      <h3><span class="badge bg-success text-white">Completed</span></h3>
    <% else %>
      <h3><span class="badge bg-warning text-white">Expired</span></h3>
    <% end %>
    </div>
  </div>
  </div>
</div>
<% end %>