config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :ratings, only: [:new, :create]
    resources :orders, only: [:new, :create, :show]
  end

  devise_for :companies
  resources :posts
  devise_for :users
  root "home#about"

  get 'home', to: 'home#home'
  get 'about', to: 'home#about'

  get '/user/profile', to: 'home#profile'
  get '/company/profile', to: 'home#company_profile'
  get '/user/services', to: 'home#services'

  get '/services/search', to: 'home#search'

  get '/user/services/search', to: 'home#filter'
  get '/company/services/search', to: 'services#filter'

  get '/company/posts', to: 'home#posts'

  get '/notification', to: 'home#notification'

  # get '/services/:service_id/payment', to: 'orders#payment', as: :payment
  # get '/pay', to: 'orders#pay'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :company_profile, :notification, :posts]
  before_action :authenticate_company!, only: [:company_profile, :posts]
  def home
  end

  def about
  end

  def profile
  end

  def company_profile
    @company = Company.find(current_company.id);
    @services = @company.services
  end

  def services
    
    @services = Service.all

    puts '-----------================---------------'
    puts params
    @search = params[:search]
    if @search && @search != ""
      @services = @services.where("lower(title) LIKE ?", "%#{@search}%")
    end

    @location = params[:location]
    if @location && @location != "" 
      @services = @services.where("lower(city) LIKE ?", @location)
    end

    @price = params[:price]
    puts @price
    p1 = 0;
    p2 = 0;
    if(@price == "1") 
      p1 = 0
      p2 = 99
    elsif(@price == "2") 
      p1 = 100
      p2 = 299
     elsif(@price == "3") 
      p1 = 300
      p2 = 599
     else 
      p1 = 600
      p2 = 100000
    
  end
    if @price && @price != "" 
      puts p1
      puts p2
      @services = @services.where("CAST(price AS INT) BETWEEN ? AND ?", p1, p2)
    end

    @rating = params[:rating]
    if @rating && @rating != "" 
      @services = @services.where("avg_rating LIKE ?", @rating)
    end
    
  end

  def filter 
    puts "filterfilterfilterfilter"
    puts params
    redirect_to :controller => 'home', :action => 'services',:search => params[:search], :location => params[:location],
      :price => params[:price], :rating => params[:rating]
  end

  def posts
    @posts = Post.where('date >= ?', Date.today).where(flag: false)
  end

  def notification
    if user_signed_in?
      @notifications = current_user.notifications.order("created_at DESC")
    elsif company_signed_in?
      @notifications = current_company.notifications.order("created_at DESC")
    end
  end

  private 
  def set_notifications_as_read
    if user_signed_in?
      notifications = current_user.notifications.unread
    elsif company_signed_in?
      notifications = current_company.notifications.unread
    end
    notifications.update_all(read_at: Time.zone.now)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% if company_signed_in? %>
    <%= render "/shared/company_navbar" %>
<% else %>
    <%= render "/shared/navbar" %>
<% end %>

<div class="p-5 mb-4 bg-body-tertiary jumbo">
    <div class="container-fluid py-5 text-center">
        <h1 class="display-5 fw-bold ">ECO PULSE</h1>
        <h1 class="fw-bold fs-3">Connect, Collect, Conserve</h1>
    </div>
</div>

<div class="about container">
    <h2 class="fw-bold">About Us: </h2>
    <p class="text text-justify m-2 mb-4">At EcoHaul, we are on a mission to transform waste management and collection into a sustainable, eco-friendly, and community-driven endeavor. Our platform is designed to connect individuals, businesses, and recycling agencies, making responsible waste disposal easier and more accessible than ever before.</p>
</div>

<div class="container card-container">
    <h2 class="fw-bold mb-2">Platform Highlights: </h2>
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-3 g-3">

        <%= render "/shared/card", title: "Simplified Scrap Listing", paragraph: "We've streamlined the process, ensuring effortless and clear listings for our users. With us, you can post scrap materials with ease, making responsible waste disposal straightforward and hassle-free", image: "about.jpeg" %>
        
        <%= render "/shared/card", title: "Eco-Consciousness at Heart", paragraph: "Our core essence is eco-consciousness. We're devoted to reducing waste, conserving resources, and championing green practices. Join us in shaping a sustainable future, one step at a time.", image: "eco.jpeg" %>

        
        <%= render "/shared/card", title: "Transparent & User-Focused", paragraph: "We pride ourselves on clear communication and intuitive design, seamless experience for every user. We value user focus, trust and responsible waste management, one interaction at a time.", image: "userfriendly.avif" %>
    
    </div>
</div>

app/views/home/company_profile.html.erb
<%= render '/shared/company_navbar' %>

<div class="container my-2">


<% if company_signed_in? %>
    <h1 class="text">Company Profile</h1>
    <div class="row">
        <div class="col col-lg-3">
            <% if current_company.company_image.attached? %>
                <%= image_tag current_company.company_image, height: 250, width: 250, class: "w-lg-100" %>
            <% else %>
                <%= image_tag "aiperson.avif", height: 250, width: 250 %>
            <% end %>
        </div>
        <div class="ms-3 col col-lg-8">
            <h1 class="text-capitalize mb-3"><%= current_company.company_name %></h1>
            <h5 class="text-secondary mb-2">Address: <%= current_company.company_address %></h5>
            <h5 class="text-secondary mb-2">Email: <%= current_company.email %></h5>
            <h5 class="text-secondary mb-2">Phone: <%= current_company.company_phone_number %></h5>
            <h5 class="text-secondary mb-2">Operational City: <%= current_company.company_city %></h5>
            <h5 class="text-secondary mb-2">Description: <%= current_company.company_description %></h5>
        </div>
        
    </div>

    <div class="m-4 d-flex align-items-center justify-content-center gap-5 px-3">
        <%= link_to "Update Profile", edit_company_registration_path, class: "fs-4 btn button-green fw-bold mb-4 col-6 p-2" %>
        <%= link_to "Create Service", new_service_path, class: "fs-4 btn button-purple text-light fw-bold mb-4 col-6 p-2" %>
    </div>

    <h1 class="mb-4 fs-2"> Available Services </h1>
    <div class="d-flex justify-content-center align-items-center flex-column">
        <% @services.each do |service| %>
            <%= render '/shared/service_post_card', service:service, flag: true %>
        <% end %>
    <div>

<% else %>

<h1>Please Sign In</h1>

<% end %>

</div>

app/views/home/home.html.erb
<div class="container home-container">
    <div class="row heading">
        <div class="col">
            <h1 class="home-heading">How do you want to use Eco Pulse?</h1>
               <div class="d-grid gap-2 col-6 button-group">
                    <%= link_to "User", new_user_registration_path, class: "btn button-green fw-bold mb-4" %>
                    <%= link_to "Agency/Company", new_company_registration_path, class: "btn button-green fw-bold" %> 
               </div>
        </div>
        <div class="col home-img-container">
            <%= image_tag "Pulse.png" %>
        </div>
    </div>
</div>

app/views/home/notification.html.erb
<% if user_signed_in? || company_signed_in? %>
  <% if user_signed_in? %>
    <%= render '/shared/navbar' %>
  <% elsif company_signed_in? %>
    <%= render '/shared/company_navbar' %>
  <% end %>

<div class="container my-2">
  <h1>Notifications</h1>
  <% if @notifications.count > 0 %>

  <ul class="list-unstyled">
    <% @notifications.unread.each do |notification| %>
      <% instance = notification.to_notification %>
      <li class="bg-primary text-light fw-bold p-2 pb-1 m-2 border rounded">
        <span>Sent at: <%= notification&.created_at.strftime('%A, %B %e, %Y %l:%M %p %Z').to_s %></span>
        <p><%= instance.message %></p>
      </li>
    <% end %>
  </ul>

  <ul class="list-unstyled">
    <% @notifications.read.each do |notification| %>
      <%= render '/shared/notification_card', notification:notification %>
    <% end %>
  </ul>
</div>

  <% if @notifications.unread.count>0 %>
    <% @notifications.unread.mark_as_read! %>
  <% end %>
<% else %>
  <h2 class="text-center">No Notifications yet<h1>
<% end %>
<% else %>
<div>
<h1>Please Login</h1>
</div>
<% end %>

app/views/home/posts.html.erb
<% if company_signed_in? %>
<%= render '/shared/company_navbar' %>
<div class="container">

<h1>Posts</h1>

<div id="posts" data-controller="search" class="d-flex justify-content-center align-items-center flex-column">
  <%= render '/shared/search_bar', flag: true %>
  <% @posts.each do |post| %>
    <%= render '/shared/user_post_card', post:post, flag: false, orderFlag: true %>
  <% end %>
</div>

</div>
<% end %>

app/views/home/profile.html.erb
<%= render '/shared/navbar' %>

<div class="container my-2">


<% if user_signed_in? %>
    <h1 class="text">User Profile</h1>
    <div class="row">
        <div class="col col-lg-3">
            <% if current_user.user_image.attached? %>
                <%= image_tag current_user.user_image, height: 250, width: 250, class: "w-lg-100" %>
            <% else %>
                <%= image_tag "aiperson.avif", height: 250, width: 250 %>
            <% end %>
        </div>
        <div class="ms-3 col col-lg-8">
            <h1 class="text-capitalize mb-4"><%= current_user.name %></h1>
            <h5 class="text-secondary mb-4">Address: <%= current_user.address %></h5>
            <h5 class="text-secondary mb-4">Email: <%= current_user.email %></h5>
            <h5 class="text-secondary mb-4">Phone: <%= current_user.phone_number %></h5>
        </div>
        
    </div>

    <div class="m-4">
        <%= link_to "Update Profile", edit_user_registration_path, class: "fs-4 btn button-green fw-bold mb-4 col-4 p-2" %>
    </div>

<% else %>

<h1>Please Sign In</h1>

<% end %>

</div>

app/views/home/services.html.erb
<% if user_signed_in? %>
<%= render '/shared/navbar' %>
<div class="container">

<h1>Services</h1>

<div id="services" data-controller="search" class="d-flex justify-content-center align-items-center flex-column">


<%= form_with url: "/user/services/search", method: :get do |form| %>
  <div class="d-flex justify-content-center col-lg-12 mb-1">
  <div class="field col-lg-7">
    <%= form.text_field :search, placeholder: "Search", class: "form-control bg-light border rounded fw-bold mb-4" %>
  </div>
  <div class="field col-lg-3 ms-2">
    <%= form.select :location, [["Bangalore", "bangalore"], ["Chennai", "chennai"], ["Mumbai", "Mumbai"]], { include_blank: "Location" }, class: "form-select bg-light fw-bold" %>
  </div>

  <div class="field col-lg-3 ms-2">
    <%= form.select :price, [["0 - 99", "1"], ["100 - 299", "2"], ["300 - 599", "3"], ["600 +", "4"]], { include_blank: "Price" }, class: "form-select bg-light fw-bold" %>
  </div>
  <div class="field col-lg-3 ms-2">
    <%= form.select :rating, [["3", "3"], ["4", "4"], ["5", "5"]], { include_blank: "Rating" }, class: "form-select bg-light fw-bold" %>
  </div>

  <div class="field">
    <%= form.submit "Search", class: "ms-1 btn button-green fw-bold" %>
  </div>

  
  
  <!-- <%= render '/shared/search_bar', flag: false %>
  <%= render '/shared/select_box', name: "Location", val: {bangalore: "Bangalore", chennai: "Chennai", mumbai: "Mumbai"}, action: "change->search#selectFilter" %>
  <%= render '/shared/select_box', name: "Price", val: {"1": "0 - 99", "2": "100 - 299", "3": "300 - 599", "4": "600 +"}, action: "change->search#priceFilter" %>
  <%= render '/shared/rating_select_box', name: "Ratings", val: {"3": "3", "4": "4", "5": "5"}, action: "change->search#ratingFilter" %>
  -->

  
  
  </div>
  <% end %>
  <!--
  <div class="d-flex">
    <% if @location %>
      <h6 class="mb-1"><%= @location.capitalize %></h6>
    <% end %>
  </div> -->

  <% if @services.count > 0 %>
    <% @services.each do |service| %>
      <%= render '/shared/service_post_card', service:service, flag: false, orderFlag: true, ratingflag:true %>
    <% end %>
  <% else %>
      <h2>No Results</h2>
      <%= link_to "Show All", user_services_path, class: "btn btn-dark" %>
  <% end %>
</div>

</div>
<% end %>